"""LibreChat — multi-provider chat UI (app + MongoDB)."""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

from puente.models import ServiceConfig

from .base import ServiceBase


class LibreChatService(ServiceBase):
    name = "librechat"
    description = "Multi-provider chat UI (frontier-alternative front end)"
    default_port = 3080
    install_method = "docker"
    docker_image = "ghcr.io/danny-avila/librechat:latest"
    requires_gpu = False

    def _render_config(self, config: ServiceConfig) -> str:
        """Render librechat.yaml. Single source of truth for both the file
        written in pre_start and the digest stamped into the compose spec."""
        ollama_base = getattr(config, "ollama_base_url", None) or "http://host.docker.internal:11434/v1"
        # An explicit list pins the picker to exactly those models; without one
        # we fetch whatever Ollama currently serves. `default` must be non-empty
        # either way (schema requirement), so it doubles as the allow-list.
        allowed = list(getattr(config, "models", None) or [])
        fetch = "false" if allowed else "true"
        if not allowed:
            allowed = ["llama3.1:8b-instruct-q4_K_M"]  # seed only; fetch replaces it
        models_yaml = "".join(f"          - '{m}'\n" for m in allowed)

        # Falls back to the last pinned model only as a last resort — `models`
        # is in picker order, not size order, so set title_model explicitly to
        # get a small one. 'current_model' is LibreChat's default and is
        # deliberately not used here — see titleModel below.
        title_model = getattr(config, "title_model", None) or allowed[-1]

        # Enforced in AuthService.registerUser — a non-matching address gets a
        # 403 at signup. This is the real gate on an open registration page;
        # it works with or without email configured.
        domains = list(getattr(config, "allowed_registration_domains", None) or [])
        registration_yaml = ""
        if domains:
            registration_yaml = "registration:\n  allowedDomains:\n" + "".join(
                f"    - '{d}'\n" for d in domains
            )

        return (
            "# Generated by puente — edits will be overwritten on `puente up`.\n"
            "version: 1.3.13\n"
            "cache: true\n"
            f"{registration_yaml}"
            "endpoints:\n"
            "  custom:\n"
            "    - name: 'Ollama'\n"
            f"      baseURL: '{ollama_base}'\n"
            "      apiKey: '${OLLAMA_API_KEY}'\n"
            "      models:\n"
            "        # fetch:false + an explicit default = the picker shows only\n"
            "        # these. fetch:true would overwrite the list from Ollama.\n"
            f"        fetch: {fetch}\n"
            "        default:\n"
            f"{models_yaml}"
            "      titleConvo: true\n"
            # Titling fires a *second* inference alongside the live chat. With
            # 'current_model' both hit the same large model and contend for the
            # card — the title request loses and aborts ("This operation was
            # aborted"), so chats stay untitled. Point this at a small model so
            # titling never competes with the conversation.
            f"      titleModel: '{title_model}'\n"
            "      modelDisplayLabel: 'Ollama'\n"
        )

    def pre_start(self, config: ServiceConfig, data_dir: str) -> None:
        """Seed librechat.yaml before the container starts.

        The file is bind-mounted, so it must exist as a *file* first — Docker
        would otherwise create a directory at that path and LibreChat would log
        "Config file YAML format is invalid" and fall back to defaults.
        Rewritten every up so endpoint changes take effect; user edits belong
        in puente.yml, not here.
        """
        target = Path(data_dir) / "librechat" / "librechat.yaml"
        target.parent.mkdir(parents=True, exist_ok=True)
        # ensure_volume_dirs() runs before this hook and mkdir -p's every bind
        # source, so on a fresh install the path already exists as a directory.
        # Clear it so the write below produces a file.
        if target.is_dir():
            target.rmdir()
        target.write_text(self._render_config(config))

    def compose_volumes(self, config: ServiceConfig) -> dict[str, dict[str, Any]]:
        return {"librechat-mongo": {}, "librechat-images": {}, "librechat-logs": {}}

    def compose_fragment(self, config: ServiceConfig, data_dir: str) -> dict[str, Any] | None:
        # external = point LibreChat elsewhere; nothing runs here.
        if getattr(config, "install_method", "docker") == "external":
            return None

        port = config.port or self.default_port
        env = dict(config.environment)
        # Bundled mongo unless the config overrides it (e.g. external Atlas).
        mongo_uri = getattr(config, "mongo_uri", None) or "mongodb://librechat-mongo:27017/LibreChat"
        env.setdefault("MONGO_URI", mongo_uri)
        # LibreChat exits at startup ("JwtStrategy requires a secret or key")
        # unless these are set. Values come from puente.yml so they stay stable
        # across recreates — regenerating them would invalidate every session
        # and make stored provider credentials undecryptable.
        for env_key, attr in (
            ("JWT_SECRET", "jwt_secret"),
            ("JWT_REFRESH_SECRET", "jwt_refresh_secret"),
            ("CREDS_KEY", "creds_key"),
            ("CREDS_IV", "creds_iv"),
        ):
            value = getattr(config, attr, None)
            if value:
                env.setdefault(env_key, value)
        # LibreChat 0.8.x defaults registration OFF. Open signup is the
        # deliberate choice here; the first account to register becomes ADMIN.
        # Override per-install via `environment: {ALLOW_REGISTRATION: 'false'}`.
        env.setdefault("ALLOW_REGISTRATION", "true")
        # Ollama is wired as a *custom endpoint* (see pre_start / librechat.yaml)
        # rather than via OPENAI_REVERSE_PROXY. The reverse-proxy route reuses the
        # built-in OpenAI endpoint, which carries a hardcoded model list, so the
        # picker shows gpt-* names instead of the locally installed Ollama models.
        # A custom endpoint with `models.fetch: true` pulls the real list from
        # /v1/models at load time. Placeholder key: Ollama needs no auth, but
        # LibreChat requires the field to be non-empty.
        env.setdefault("OLLAMA_API_KEY", "ollama")
        env.setdefault("CONFIG_PATH", "/app/librechat.yaml")

        # Anthropic endpoint. LibreChat has native Claude support, so this is a
        # first-class endpoint rather than a custom OpenAI-compatible one.
        # ANTHROPIC_MODELS pins the picker to the listed models.
        key_env = getattr(config, "anthropic_key_env", None)
        if key_env:
            # `user_provided` is a literal sentinel, not an env var name.
            env.setdefault(
                "ANTHROPIC_API_KEY",
                key_env if key_env == "user_provided" else f"${{{key_env}}}",
            )
            claude_models = list(getattr(config, "anthropic_models", None) or [])
            if claude_models:
                env.setdefault("ANTHROPIC_MODELS", ",".join(claude_models))

        # SMTP. When EMAIL_HOST is set LibreChat sends a verification link on
        # signup and enables self-service password reset; without it, accounts
        # are auto-verified and reset is disabled entirely.
        email_host = getattr(config, "email_host", None)
        if email_host:
            env.setdefault("EMAIL_HOST", email_host)
            env.setdefault("EMAIL_PORT", str(getattr(config, "email_port", None) or 587))
            env.setdefault("EMAIL_USERNAME", getattr(config, "email_username", None) or "resend")
            env.setdefault("EMAIL_FROM", getattr(config, "email_from", None) or "")
            env.setdefault("EMAIL_FROM_NAME", getattr(config, "email_from_name", None) or "LibreChat")
            # Password comes from the host environment so the secret stays out
            # of puente.yml; compose interpolates ${VAR} at up time.
            pw_env = getattr(config, "email_password_env", None) or "RESEND_API_KEY"
            env.setdefault("EMAIL_PASSWORD", f"${{{pw_env}}}")
            # Password reset has its own switch — configuring SMTP is not enough.
            # Only meaningful with email working, hence nested here.
            env.setdefault("ALLOW_PASSWORD_RESET", "true")

        # librechat.yaml is bind-mounted and only read at boot, so editing it
        # is invisible to compose — it would report "Running" and leave the old
        # config live. Stamping its hash into a label makes the container spec
        # change, so compose recreates and the new config actually takes effect.
        config_digest = hashlib.sha256(
            self._render_config(config).encode()
        ).hexdigest()[:12]

        fragment: dict[str, Any] = {
            "librechat": {
                "image": self.docker_image,
                "container_name": "puente-librechat",
                "ports": [f"{port}:3080"],
                "environment": env,
                "labels": {"puente.config-digest": config_digest},
                "extra_hosts": ["host.docker.internal:host-gateway"],
                "volumes": [
                    "librechat-images:/app/client/public/images",
                    "librechat-logs:/app/api/logs",
                    f"{data_dir}/librechat/librechat.yaml:/app/librechat.yaml:ro",
                ],
                "depends_on": ["librechat-mongo"],
                "restart": "unless-stopped",
            }
        }
        # Only run the bundled mongo when not using an external one.
        if not getattr(config, "mongo_uri", None):
            fragment["librechat-mongo"] = {
                "image": "mongo:7",
                "container_name": "puente-librechat-mongo",
                "command": "mongod --noauth",
                "volumes": ["librechat-mongo:/data/db"],
                "restart": "unless-stopped",
            }

        return fragment
