"""Caddyfile generation from service proxy blocks.

Mirrors ``compose.py``: walks the enabled services and projects each one's
``proxy:`` block into a Caddy site. The Caddyfile is therefore *derived* from
``puente.yml`` — there is no second source of truth to drift, and the portal
reads the same proxy config to build its links.
"""

from __future__ import annotations

from pathlib import Path

from puente.models import CaddyConfig, ProxyConfig, PuenteConfig, ServiceConfig


def _port_for(svc_name: str, svc_config: ServiceConfig) -> int | None:
    """Resolve the upstream port for a service (config override or class default)."""
    if svc_config.port is not None:
        return svc_config.port
    # Lazy import avoids a circular dependency: puente.services.caddy imports
    # this module, and puente.services.__init__ imports that service.
    from puente.services import ALL_SERVICES

    svc_class = ALL_SERVICES.get(svc_name)
    return getattr(svc_class, "default_port", None) if svc_class else None


def iter_proxied_services(config: PuenteConfig):
    """Yield (svc_name, ServiceConfig, ProxyConfig) for every service that
    declares a proxy block — once per hostname (a service may list several).

    A declared proxy block is served whether or not the service is enabled: the
    user controls the boundary, not puente. A block on a stopped service just
    proxies to a dead upstream (502) — not puente's concern. Registry order.
    """
    from puente.services import ALL_SERVICES

    for svc_name in ALL_SERVICES:
        svc_config = getattr(config.services, svc_name, None)
        if svc_config is None or svc_config.proxy is None:
            continue
        blocks = svc_config.proxy
        if not isinstance(blocks, list):
            blocks = [blocks]
        for proxy in blocks:
            yield svc_name, svc_config, proxy


def _site_block(
    proxy: ProxyConfig,
    upstream: str,
    port: int,
    caddy: CaddyConfig,
) -> str:
    """Render one Caddy site block for a proxied service."""
    lines = [f"{proxy.host} {{"]

    if proxy.auth == "basic":
        group = proxy.basic_group
        if group is None:
            # Default: the sole group, else a conventional "ui" group.
            if len(caddy.users) == 1:
                group = next(iter(caddy.users))
            elif "ui" in caddy.users:
                group = "ui"
        users = caddy.users.get(group, {}) if group else {}
        if not users:
            raise ValueError(
                f"basic_auth host {proxy.host!r} resolved to no users "
                f"(basic_group={proxy.basic_group!r}); set proxy.basic_group to "
                f"one of {sorted(caddy.users)} or define that group in caddy.users"
            )
        lines.append("\tbasic_auth {")
        for username, value in users.items():
            # A value starting with "$2" is a literal bcrypt hash: emit it
            # inline (no env indirection). Anything else is treated as the
            # name of an env var and rendered as a {$VAR} placeholder.
            if value.startswith("$2"):
                lines.append(f"\t\t{username} {value}")
            else:
                lines.append(f"\t\t{username} {{${value}}}")
        lines.append("\t}")
    elif proxy.auth == "bearer":
        # token read from the container environment; matcher rejects anything
        # that isn't exactly "Bearer <token>".
        env = proxy.token_env or ""
        lines.append(
            f'\t@unauthorized not header Authorization "Bearer {{${env}}}"'
        )
        lines.append("\trespond @unauthorized 401")

    lines.append(f"\treverse_proxy {upstream}:{port}")
    lines.append("}")
    return "\n".join(lines)


def generate_caddyfile(config: PuenteConfig) -> str:
    """Build the full Caddyfile text from enabled services' proxy blocks."""
    caddy = config.services.caddy
    upstream = caddy.upstream_host

    header = [
        "# ==========================================================================",
        "# GENERATED by puente from puente.yml — do not edit by hand.",
        "# Add a `proxy:` block to a service in puente.yml and re-run to regenerate.",
        "# ==========================================================================",
        "",
    ]

    if caddy.email:
        header += ["{", f"\temail {caddy.email}", "}", ""]

    blocks: list[str] = []

    # Service-bound proxy blocks.
    for svc_name, svc_config, proxy in iter_proxied_services(config):
        # Per-block port override wins, else the service's own port.
        port = proxy.port if proxy.port is not None else _port_for(svc_name, svc_config)
        if port is None:
            # No port to proxy to; skip rather than emit a broken upstream.
            continue
        blocks.append(_site_block(proxy, proxy.upstream or upstream, port, caddy))

    # Standalone hosts not tied to any puente service.
    for proxy in caddy.proxy_hosts:
        if proxy.port is None:
            # A standalone host has no service to borrow a port from.
            continue
        blocks.append(_site_block(proxy, proxy.upstream or upstream, proxy.port, caddy))

    return "\n".join(header) + "\n\n".join(blocks) + "\n"


def write_caddyfile(config: PuenteConfig, output_path: Path | None = None) -> Path:
    """Generate and write the Caddyfile under the data dir."""
    text = generate_caddyfile(config)
    path = output_path or config.resolved_data_dir() / "caddy" / "Caddyfile"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path


def proxy_urls(config: PuenteConfig) -> dict[str, str]:
    """Map service name -> public https URL, derived from proxy blocks.

    Replaces the hand-maintained PROXY_URLS dict in portal.py.
    """
    out: dict[str, str] = {}
    for svc_name, _cfg, proxy in iter_proxied_services(config):
        # First hostname wins — a service's primary public URL for the portal.
        out.setdefault(svc_name, f"https://{proxy.host}")
    return out
