"""Caddyfile generation from service proxy blocks.

Mirrors ``compose.py``: walks the enabled services and projects each one's
``proxy:`` block into a Caddy site. The Caddyfile is therefore *derived* from
``puente.yml`` — there is no second source of truth to drift, and the portal
reads the same proxy config to build its links.
"""

from __future__ import annotations

from pathlib import Path

from puente.models import CaddyConfig, ProxyConfig, PuenteConfig, ServiceConfig


def _port_for(svc_name: str, svc_config: ServiceConfig) -> int | None:
    """Resolve the upstream port for a service (config override or class default)."""
    if svc_config.port is not None:
        return svc_config.port
    # Lazy import avoids a circular dependency: puente.services.caddy imports
    # this module, and puente.services.__init__ imports that service.
    from puente.services import ALL_SERVICES

    svc_class = ALL_SERVICES.get(svc_name)
    return getattr(svc_class, "default_port", None) if svc_class else None


def iter_proxied_services(config: PuenteConfig):
    """Yield (svc_name, ServiceConfig, ProxyConfig) for every enabled service
    that declares a proxy block. Stable order = registry order.
    """
    from puente.services import ALL_SERVICES

    for svc_name in ALL_SERVICES:
        svc_config = getattr(config.services, svc_name, None)
        if svc_config is None or not svc_config.enabled:
            continue
        if svc_config.proxy is None:
            continue
        yield svc_name, svc_config, svc_config.proxy


def _site_block(
    proxy: ProxyConfig,
    upstream: str,
    port: int,
    caddy: CaddyConfig,
) -> str:
    """Render one Caddy site block for a proxied service."""
    lines = [f"{proxy.host} {{"]

    if proxy.auth == "basic":
        group = proxy.basic_group
        if group is None and len(caddy.users) == 1:
            group = next(iter(caddy.users))
        users = caddy.users.get(group, {}) if group else {}
        lines.append("\tbasic_auth {")
        for username, env_var in users.items():
            lines.append(f"\t\t{username} {{${env_var}}}")
        lines.append("\t}")
    elif proxy.auth == "bearer":
        # token read from the container environment; matcher rejects anything
        # that isn't exactly "Bearer <token>".
        env = proxy.token_env or ""
        lines.append(
            f'\t@unauthorized not header Authorization "Bearer {{${env}}}"'
        )
        lines.append("\trespond @unauthorized 401")

    lines.append(f"\treverse_proxy {upstream}:{port}")
    lines.append("}")
    return "\n".join(lines)


def generate_caddyfile(config: PuenteConfig) -> str:
    """Build the full Caddyfile text from enabled services' proxy blocks."""
    caddy = config.services.caddy
    upstream = caddy.upstream_host

    header = [
        "# ==========================================================================",
        "# GENERATED by puente from puente.yml — do not edit by hand.",
        "# Add a `proxy:` block to a service in puente.yml and re-run to regenerate.",
        "# ==========================================================================",
        "",
    ]

    if caddy.email:
        header += ["{", f"\temail {caddy.email}", "}", ""]

    blocks: list[str] = []
    for svc_name, svc_config, proxy in iter_proxied_services(config):
        port = _port_for(svc_name, svc_config)
        if port is None:
            # No port to proxy to; skip rather than emit a broken upstream.
            continue
        blocks.append(_site_block(proxy, upstream, port, caddy))

    return "\n".join(header) + "\n\n".join(blocks) + "\n"


def write_caddyfile(config: PuenteConfig, output_path: Path | None = None) -> Path:
    """Generate and write the Caddyfile under the data dir."""
    text = generate_caddyfile(config)
    path = output_path or config.resolved_data_dir() / "caddy" / "Caddyfile"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path


def proxy_urls(config: PuenteConfig) -> dict[str, str]:
    """Map service name -> public https URL, derived from proxy blocks.

    Replaces the hand-maintained PROXY_URLS dict in portal.py.
    """
    return {
        svc_name: f"https://{proxy.host}"
        for svc_name, _cfg, proxy in iter_proxied_services(config)
    }
